project:
  type: website
  output-dir: docs

website:
  title: "Home"
  search: false
        
format:
  html:
    linkcolor: "#1f77b4"
    link-external-icon: true
    highlight-style: grayscale
    reference-location: margin
    theme: [cosmo, styles.scss]

