project:
  type: website
  output-dir: docs

website:
  title: "Home"
  open-graph: true 
  page-footer: ""
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv.qmd
        
format:
  html:
    linkcolor: "#1f77b4"
    link-external-icon: true
    highlight-style: grayscale
    html-math-method: webtex # webtex
    html-table-processing: none
    mainfont: Latin Modern Roman
    monofont: Latin Modern Mono
    reference-location: margin
    theme: [cosmo, styles.scss]

